-- tables
DROP TABLE CITY CASCADE CONSTRAINTS;

DROP TABLE COUNTY CASCADE CONSTRAINTS;

DROP TABLE FACILITY CASCADE CONSTRAINTS;

DROP TABLE FACILITY_LOCATION CASCADE CONSTRAINTS;

DROP TABLE HEALTH_DEPARTMENT_INSPECTION CASCADE CONSTRAINTS;

DROP TABLE INSPECTION CASCADE CONSTRAINTS;

DROP TABLE INSPECTION_TYPE CASCADE CONSTRAINTS;

DROP TABLE LOCAL_HEALTH_DEPARTMENT CASCADE CONSTRAINTS;

DROP TABLE MUNICIPALITY CASCADE CONSTRAINTS;

DROP TABLE PERMIT CASCADE CONSTRAINTS;

DROP TABLE PERM_OPERATOR CASCADE CONSTRAINTS;

DROP TABLE PERM_OPERATOR_PERMIT CASCADE CONSTRAINTS;

DROP TABLE STATE CASCADE CONSTRAINTS;

DROP TABLE VIOLATION CASCADE CONSTRAINTS;

DROP TABLE VIOLATION_INSPECTION CASCADE CONSTRAINTS;

-- tables
-- Table: CITY
CREATE TABLE CITY (
    CITY_ID integer  NOT NULL,
    CITY_NAME varchar2(255)  NOT NULL,
    STATE_ID integer  NOT NULL,
    CONSTRAINT CITY_pk PRIMARY KEY (CITY_ID,STATE_ID)
) ;

-- Table: COUNTY
CREATE TABLE COUNTY (
    COUNTY_ID integer  NOT NULL,
    COUNTY_NAME varchar2(50)  NOT NULL,
    STATE_ID integer  NOT NULL,
    CONSTRAINT COUNTY_pk PRIMARY KEY (COUNTY_ID,STATE_ID)
) ;

-- Table: FACILITY
CREATE TABLE FACILITY (
    FACILITY_ID integer  NOT NULL,
    FACILITY_NAME varchar2(255)  NOT NULL,
    DESCRIPTION varchar2(255)  NOT NULL,
    NYSDOH_GAZETTEER_1980 integer  NOT NULL,
    CONSTRAINT FACILITY_pk PRIMARY KEY (FACILITY_ID)
) ;

-- Table: FACILITY_LOCATION
CREATE TABLE FACILITY_LOCATION (
    FACILITY_LOCATION_ID integer  NOT NULL,
    FACILITY_ADDRESS varchar2(255)  NOT NULL,
    ZIP_CODE varchar2(10)  NULL,
    LATITUDE number(9,6)  NOT NULL,
    LONGTITUDE number(9,6)  NOT NULL,
    MUNICIPALITY_ID integer  NOT NULL,
    CITY_ID integer  NOT NULL,
    COUNTY_ID integer  NOT NULL,
    FOOD_SERVICE_FACILITY_STATE_ID integer  NOT NULL,
    FACILITY_ID integer  NOT NULL,
    CONSTRAINT FACILITY_LOCATION_pk PRIMARY KEY (FACILITY_LOCATION_ID)
) ;

-- Table: HEALTH_DEPARTMENT_INSPECTION
CREATE TABLE HEALTH_DEPARTMENT_INSPECTION (
    LOCAL_HEALTH_DEPARTMENT_ID integer  NOT NULL,
    INSPECTION_ID integer  NOT NULL
) ;

-- Table: INSPECTION
CREATE TABLE INSPECTION (
    INSPECTION_ID integer  NOT NULL,
    INSPECTION_DATE date  NOT NULL,
    TOTAL_CRITICAL_VIOLATIONS integer  NULL,
    TOTAL_CRITICAL_NOT_CORRECTED integer  NULL,
    TOTAL_NONCRITICAL_VIOLATIONS integer  NULL,
    INSPECTION_COMMENTS varchar2(3000)  NULL,
    INSPECTION_TYPE_ID integer  NOT NULL,
    FACILITY_ID integer  NOT NULL,
    OPERATION_NAME varchar2(255)  NOT NULL,
    NYS_HEALTH_OPERATION_ID integer  NOT NULL,
    CONSTRAINT INSPECTION_pk PRIMARY KEY (INSPECTION_ID)
) ;

-- Table: INSPECTION_TYPE
CREATE TABLE INSPECTION_TYPE (
    INSPECTION_TYPE_ID integer  NOT NULL,
    INSPECTION_TYPE_DESCRIPTION varchar2(255)  NOT NULL,
    CONSTRAINT INSPECTION_TYPE_pk PRIMARY KEY (INSPECTION_TYPE_ID)
) ;

-- Table: LOCAL_HEALTH_DEPARTMENT
CREATE TABLE LOCAL_HEALTH_DEPARTMENT (
    LOCAL_HEALTH_DEPARTMENT_ID integer  NOT NULL,
    LOCAL_HEALTH_DEPARTMENT_NAME varchar2(255)  NOT NULL,
    CONSTRAINT LOCAL_HEALTH_DEPARTMENT_pk PRIMARY KEY (LOCAL_HEALTH_DEPARTMENT_ID)
) ;

-- Table: MUNICIPALITY
CREATE TABLE MUNICIPALITY (
    MUNICIPALITY_ID integer  NOT NULL,
    MUNICIPALITY_NAME varchar2(50)  NOT NULL,
    STATE_ID integer  NOT NULL,
    CONSTRAINT MUNICIPALITY_pk PRIMARY KEY (MUNICIPALITY_ID,STATE_ID)
) ;

-- Table: PERMIT
CREATE TABLE PERMIT (
    PERMIT_ID integer  NOT NULL,
    PERMITTED_D_B_A varchar2(255)  NULL,
    PERMITTED_CORP_NAME varchar2(255)  NULL,
    PERMIT_EXPIRATION_DATE date  NOT NULL,
    FACILITY_ID integer  NOT NULL,
    CONSTRAINT PERMIT_pk PRIMARY KEY (PERMIT_ID)
) ;

-- Table: PERM_OPERATOR
CREATE TABLE PERM_OPERATOR (
    PERM_OPERATOR_ID integer  NOT NULL,
    PERM_OPERATOR_FIRST_NAME varchar2(255)  NULL,
    PERM_OPERATOR_LAST_NAME varchar2(255)  NULL,
    CONSTRAINT PERM_OPERATOR_pk PRIMARY KEY (PERM_OPERATOR_ID)
) ;

-- Table: PERM_OPERATOR_PERMIT
CREATE TABLE PERM_OPERATOR_PERMIT (
    PERM_OPERATOR_ID integer  NULL,
    PERMIT_ID integer  NOT NULL
) ;

-- Table: STATE
CREATE TABLE STATE (
    STATE_ID integer  NOT NULL,
    STATE_NAME varchar2(255)  NOT NULL,
    CONSTRAINT STATE_pk PRIMARY KEY (STATE_ID)
) ;

-- Table: VIOLATION
CREATE TABLE VIOLATION (
    VIOLATION_ID varchar2(5) NOT NULL,
    VIOLATION_DESCRIPTION varchar2(300) NULL,
    CONSTRAINT VIOLATION_pk PRIMARY KEY (VIOLATION_ID)
);

-- Table: VIOLATION_INSPECTION
CREATE TABLE VIOLATION_INSPECTION (
    VIOLATION_ID varchar2(5)  NULL,
    INSPECTION_ID integer  NOT NULL
) ;

-- foreign keys
-- Reference: CITY_STATE (table: CITY)
ALTER TABLE CITY ADD CONSTRAINT CITY_STATE
    FOREIGN KEY (STATE_ID)
    REFERENCES STATE (STATE_ID);

-- Reference: COUNTY_STATE (table: COUNTY)
ALTER TABLE COUNTY ADD CONSTRAINT COUNTY_STATE
    FOREIGN KEY (STATE_ID)
    REFERENCES STATE (STATE_ID);

-- Reference: FACILITY_HEALTH_DEPARTMENT_INSPECTION (table: HEALTH_DEPARTMENT_INSPECTION)
ALTER TABLE HEALTH_DEPARTMENT_INSPECTION ADD CONSTRAINT FACILITY_HEALTH_DEPARTMENT_INSPECTION
    FOREIGN KEY (INSPECTION_ID)
    REFERENCES INSPECTION (INSPECTION_ID);

-- Reference: FACILITY_HEALTH_DEPARTMENT_LOCAL_HEALTH_DEPARTMENT (table: HEALTH_DEPARTMENT_INSPECTION)
ALTER TABLE HEALTH_DEPARTMENT_INSPECTION ADD CONSTRAINT FACILITY_HEALTH_DEPARTMENT_LOCAL_HEALTH_DEPARTMENT
    FOREIGN KEY (LOCAL_HEALTH_DEPARTMENT_ID)
    REFERENCES LOCAL_HEALTH_DEPARTMENT (LOCAL_HEALTH_DEPARTMENT_ID);

-- Reference: FACILITY_LOCATION_CITY (table: FACILITY_LOCATION)
ALTER TABLE FACILITY_LOCATION ADD CONSTRAINT FACILITY_LOCATION_CITY
    FOREIGN KEY (CITY_ID,FOOD_SERVICE_FACILITY_STATE_ID)
    REFERENCES CITY (CITY_ID,STATE_ID);

-- Reference: FACILITY_LOCATION_COUNTY (table: FACILITY_LOCATION)
ALTER TABLE FACILITY_LOCATION ADD CONSTRAINT FACILITY_LOCATION_COUNTY
    FOREIGN KEY (COUNTY_ID,FOOD_SERVICE_FACILITY_STATE_ID)
    REFERENCES COUNTY (COUNTY_ID,STATE_ID);

-- Reference: FACILITY_LOCATION_FACILITY (table: FACILITY_LOCATION)
ALTER TABLE FACILITY_LOCATION ADD CONSTRAINT FACILITY_LOCATION_FACILITY
    FOREIGN KEY (FACILITY_ID)
    REFERENCES FACILITY (FACILITY_ID);

-- Reference: FACILITY_LOCATION_MUNICIPALITY (table: FACILITY_LOCATION)
ALTER TABLE FACILITY_LOCATION ADD CONSTRAINT FACILITY_LOCATION_MUNICIPALITY
    FOREIGN KEY (MUNICIPALITY_ID,FOOD_SERVICE_FACILITY_STATE_ID)
    REFERENCES MUNICIPALITY (MUNICIPALITY_ID,STATE_ID);

-- Reference: INSPECTION_FACILITY (table: INSPECTION)
ALTER TABLE INSPECTION ADD CONSTRAINT INSPECTION_FACILITY
    FOREIGN KEY (FACILITY_ID)
    REFERENCES FACILITY (FACILITY_ID);

-- Reference: INSPECTION_TYPE (table: INSPECTION)
ALTER TABLE INSPECTION ADD CONSTRAINT INSPECTION_TYPE
    FOREIGN KEY (INSPECTION_TYPE_ID)
    REFERENCES INSPECTION_TYPE (INSPECTION_TYPE_ID);

-- Reference: PERMIT_FACILITY (table: PERMIT)
ALTER TABLE PERMIT ADD CONSTRAINT PERMIT_FACILITY
    FOREIGN KEY (FACILITY_ID)
    REFERENCES FACILITY (FACILITY_ID);

-- Reference: PERM_OPERATOR_PERMIT_PERMIT (table: PERM_OPERATOR_PERMIT)
ALTER TABLE PERM_OPERATOR_PERMIT ADD CONSTRAINT PERM_OPERATOR_PERMIT_PERMIT
    FOREIGN KEY (PERMIT_ID)
    REFERENCES PERMIT (PERMIT_ID);

-- Reference: PERM_OPERATOR_PERMIT_PERM_OPERATOR (table: PERM_OPERATOR_PERMIT)
ALTER TABLE PERM_OPERATOR_PERMIT ADD CONSTRAINT PERM_OPERATOR_PERMIT_PERM_OPERATOR
    FOREIGN KEY (PERM_OPERATOR_ID)
    REFERENCES PERM_OPERATOR (PERM_OPERATOR_ID);

-- Reference: VIOLATION_INSPECTION (table: VIOLATION_INSPECTION)
ALTER TABLE VIOLATION_INSPECTION ADD CONSTRAINT VIOLATION_INSPECTION
    FOREIGN KEY (INSPECTION_ID)
    REFERENCES INSPECTION (INSPECTION_ID);

-- Reference: VIOLATION_INSPECTION_VIOLATION (table: VIOLATION_INSPECTION)
ALTER TABLE VIOLATION_INSPECTION ADD CONSTRAINT VIOLATION_INSPECTION_VIOLATION
    FOREIGN KEY (VIOLATION_ID)
    REFERENCES VIOLATION (VIOLATION_ID);